---
- name: Install apache
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_yum_packages }}"
- name: enable apache
  service:
    name: "{{ apache_service_name }}"
    state: started
- name: Copy Index file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart apache
- name: Copy apache configuration files
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart apache
