---
- name: Install epel repo
  shell: rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm --force
- name: Install Wordpress
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wordpress_packages }}"
- name: Apache config file for Wordpress
  template:
    src: wordpress.conf.j2
    dest: "{{ wordpress_httpd_configuration }}"
    owner: root
    group: root
    mode: '0644'
- name: Download Salts
  get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: "{{ wordpress_directory }}/wp-salts.php"
    seuser: system_u
    setype: httpd_sys_script_exec_t
    force: no
  notify: restart httpd

- name: Insert PHP start tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '<?php'
    state: present
    insertbefore: BOF
  notify: restart httpd

- name: Insert PHP end tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '?>'
    state: present
    insertafter: EOF
  notify: restart httpd

- name: Wordpress config file
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_configuration }}"
    owner: root
    group: apache
    mode: '0640'
  notify: restart httpd
